spring.application.name=reviewer
server.port=8765

spring.servlet.multipart.enabled=true
# spring.servlet.multipart.max-file-size=5MB
# spring.servlet.multipart.max-request-size=50MB
# server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-part-count=100
